grid_clb:
  - grid_clb_config_group_mem_size885
grid_io_bottomL_bottom:
  - grid_io_bottomL_bottom_config_group_mem_size140
grid_io_leftL_left:
  - grid_io_leftL_left_config_group_mem_size136
grid_io_rightL_right:
  - grid_io_rightL_right_config_group_mem_size136
grid_io_topL_top:
  - grid_io_topL_top_config_group_mem_size136
sb_0_:
  - sb_0__config_group_mem_size265
sb_1_:
  - sb_1__config_group_mem_size344
sb_2_:
  - sb_2__config_group_mem_size408
sb_3_:
  - sb_3__config_group_mem_size344
sb_4_:
  - sb_4__config_group_mem_size244
sb_6_:
  - sb_6__config_group_mem_size340
sb_7_:
  - sb_7__config_group_mem_size358
sb_8_:
  - sb_8__config_group_mem_size360
sb_10_:
  - sb_10__config_group_mem_size336
sb_11_:
  - sb_11__config_group_mem_size358
sb_12_:
  - sb_12__config_group_mem_size315
cbx_2_:
  - cbx_2__config_group_mem_size32
cbx_3_:
  - cbx_3__config_group_mem_size174
cbx_4_:
  - cbx_4__config_group_mem_size206
cbx_5_:
  - cbx_5__config_group_mem_size174
cbx_6_:
  - cbx_6__config_group_mem_size206
cby_1_:
  - cby_1__config_group_mem_size224
cby_2_:
  - cby_2__config_group_mem_size176
cby_3_:
  - cby_3__config_group_mem_size336
cby_4_:
  - cby_4__config_group_mem_size336
cby_5_:
  - cby_5__config_group_mem_size560
cby_6_:
  - cby_6__config_group_mem_size560
