name: cccccc

on:
  workflow_run:
    workflows: ["Create release package"]
    types: [completed]

jobs:
  upload_docs:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      actions: read
      contents: write

    steps:
      - name: Print workflow_run conclusion
        run: echo "workflow_run conclusion ${{ github.event.workflow_run.conclusion }}"